name: Prettify Code

on:
  push:
    branches:
      - main # Adjust this branch name according to your main branch
      - minimal-new-front
      - deploy-test

jobs:
  prettify:
    name: Prettify Code
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Install Dependencies
        run: yarn install

      - name: Run Prettier
        run: yarn run format

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git diff-index --quiet HEAD || git commit -m "Prettify code" || exit 0
          git push
